[package]
name = "mame"
version = "0.0.0"
edition = "2021"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
license = "MIT"
description = "TUI text editor"
homepage = "https://github.com/sile/mame"
repository = "https://github.com/sile/mame"
readme = "README.md"

[dependencies]
crossterm = { version = "0.28.1", default-features=false, features = ["events", "bracketed-paste", "serde"] }
jsonlrpc = "0.2.2"
jsonlrpc_mio = "0.2.1"
libc = "0.2.169"
log = "0.4.22"
mio = { version = "1.0.3", default-features = false, features = ["os-ext", "os-poll", "net"] }
orfail = "1.1.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
simplelog = { version = "0.12.2", default-features = false, features = ["local-offset"] }
